### PR TITLE
Add freecad icon

### PR DESCRIPTION
**Pull request by martinRenou**
Fix https://github.com/jupytercad/JupyterCAD-FreeCAD/issues/14

Screenshot From 2024-11-29 15-53-57

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I think the highlighted icon should probably become white like other file icons.

**Comment by martinRenou** [comment]
> Actually I'm not sure I agree 😆
> 
> Screenshot From 2024-12-02 11-02-17

**Comment by SylvainCorlay** [comment]
> Actually I'm not sure I agree 😆

If the `F`-shaped central area takes the background color when highlighted, that could work.

**Comment by martinRenou** [comment]
https://github.com/user-attachments/assets/088f5554-0e58-463e-b11c-023fdafe8013

**Comment by martinRenou** [comment]
It looks like the CI cannot be trusted anymore, I'll just merge

**Comment by SylvainCorlay** [comment]
> It looks like the CI cannot be trusted anymore, I'll just merge

💯 we should never trust CI 😆

**Pull request merged**
