### PR TITLE
Bump `@jupyter/collaboration` to v3

### LINKED ISSUE #16: Bump jupyter-collaboration to 3.0.0

### PR DESCRIPTION
**Pull request by arjxn-py**
Shall Close #16

### CODE REVIEW

**Comment by arjxn-py** [comment]
Please update snapshots

**Comment by arjxn-py** [comment]
Please update snapshots

**Comment by trungleduc** [comment]
Failed CI tests look legit. Does it work locally for you?

**Comment by arjxn-py** [comment]
> Failed CI tests look legit. Does it work locally for you?

Nope. It has not been working lately and was not working before the changes too

image

**Review by martinRenou — APPROVED** [review]
Thanks!!

**Pull request merged**
