### PR TITLE
Update JupyterCAD

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by trungleduc** [comment]
We might need to update the test script to click on the ok button

[video.webm](https://github.com/jupytercad/JupyterCAD-FreeCAD/assets/4451292/9145bdf6-71b5-4b65-932b-ce4cf8311c28)

**Comment by martinRenou** [comment]
Thanks for looking into it, I'll make the change.

It's annoying though that playwright did not report a video, or did I miss it?

**Comment by martinRenou** [comment]
please update snapshots

**Comment by trungleduc** [comment]
> Thanks for looking into it, I'll make the change.
> 
> It's annoying though that playwright did not report a video, or did I miss it?

there are some changes in lab 4.2 about galata. I pinned lab 4.1.2 in the UI test for now

**Pull request merged**
